ALTER TABLE core.products 
ADD COLUMN IF NOT EXISTS original_price INT,
DROP COLUMN IF EXISTS image_url,
ADD COLUMN IF NOT EXISTS image_url TEXT[],
ADD COLUMN IF NOT EXISTS sizes TEXT[],
ADD COLUMN IF NOT EXISTS colors TEXT[],
ADD COLUMN IF NOT EXISTS rating INT,
ADD COLUMN IF NOT EXISTS reviews JSON
